Update inclusive-leadership.md
chaoss/wg-dei pull request #360
Opened 2021-04-21 14:43 UTC by germonprez

Signed-off-by: Matt Germonprez <germonprez@gmail.com>

Updating the Inclusive Leadership metric to: 

1) Be a bit more explicit as to what the metric is about
2) Align with the CHAOSS metrics template.

2021-04-21 15:10 UTC, Nebrethar commented on focus-areas/leadership/inclusive-leadership.md
> +The first step is to understand the principles of inclusive leadership by asking some questions that can include.
What is the second half of this sentence?

2021-04-21 15:10 UTC, Nebrethar commented on focus-areas/leadership/inclusive-leadership.md
> +* People serving as project maintainers (sometimes referred to as owners)
Recommend using "Individuals" instead of "people" here

2021-04-21 15:10 UTC, Nebrethar commented on focus-areas/leadership/inclusive-leadership.md
> +Question: How well is a project/community setup for diverse leadership?
Recommend "project and community" instead of "project/community"

2021-05-26 17:57 UTC, jwflory requested changes
These changes look great to me. I had some small changes that I left as GitHub Suggestions in this review. The biggest change I made was clarifying the vocabulary on `project/community` and `project and community` into `project community`.

Also some questions, see in-line comments.

2021-05-26 17:57 UTC, jwflory commented on focus-areas/leadership/inclusive-leadership.md
> +Question: How well is a project and community setup for diverse leadership?
I find the `project and community` and `project/community` wording confusing. Are they the same? Are they different? I feel when we use this term, we are usually referring to the community of people gathered around the tech project. So, I believe `project community` is a subtle wording change, but it conveys a more clear meaning in the delivery on this metric.

```suggestion
Question: How well is a project community setup for diverse leadership?
```

2021-05-26 17:57 UTC, jwflory commented on focus-areas/leadership/inclusive-leadership.md
> +Leadership is central to a project/community's culture and how the leadership is determined requires intentional design and accountability for the inclusion of others. Note the term leadership may va
Small revision.

```suggestion
Leadership is central to a project community's culture. Project leadership models requires intentional design and accountability for the inclusion of others. Note the term leadership may vary depending on community. Leadership roles have high visibility and should be well-connected to others in the project. The diversity of this group is critically important to fostering an inclusive community.
```

2021-05-26 17:57 UTC, jwflory commented on focus-areas/leadership/inclusive-leadership.md
> +- Signal to newcomers that everyone is welcome, has an opportunity to take on leadership roles, and can be successful within the project.
Is this an objective of the metric itself, or an objective of someone implementing this metric in practice?

2021-05-26 17:57 UTC, jwflory commented on focus-areas/leadership/inclusive-leadership.md
> +* Individuals with repository merge access
```suggestion
* Individuals with repository commit access (sometimes referred to as committers)
```

2021-05-26 17:57 UTC, jwflory commented on focus-areas/leadership/inclusive-leadership.md
> +The third step is to act on what you've learned. What those steps are depends on your specific project community and giving recommendations is outside the scope of this document.
Looks like `project community` was already used in other places in the document too. 😁

2021-10-06 15:18 UTC, merged