New Metrics Update:  Issue-label-inclusivity.md
chaoss/wg-dei pull request #527
Opened 2024-09-16 00:52 UTC by peculiaruc

Updated the Organizational Influence using the new metrics template

- Tweak the description and the objective sections to form the Overview section.
- Remove Tool Providing metric section e.t.c

2024-09-26 18:45 UTC, germonprez commented on focus-areas/project-and-community/issue-label-inclusivity.md
> +Issue Label Inclusivity measures the accessibility and inclusiveness of project issues for contributors of various skill levels and backgrounds. Data points include the number and types of labels use
Recommended edits: 

Issue Label Inclusivity measures the accessibility and inclusiveness of project issues for contributors of various skill levels and backgrounds. Data points include the number and types of labels used, the clarity of issue titles and descriptions, and the presence of labels that indicate the level of skills needed to tackle the issue. The Issue Label Inclusivity metric can help a project ensure: newcomer friendly issues are created, issue list diversity, usable titles and descriptions, and consistent use of labels to identify types of contributor or skill level needed to work on an issue.

2024-09-26 18:47 UTC, germonprez commented on focus-areas/project-and-community/issue-label-inclusivity.md
> +
Could you please remove the '(labels in use)' from the end of every sentence?

2024-09-26 18:57 UTC, ElizabethN requested changes

2024-09-26 18:57 UTC, ElizabethN commented on focus-areas/project-and-community/issue-label-inclusivity.md
> +Inclusive labelling practices help to create a more equitable and accessible environment for contributors from all backgrounds. Providing clear and informative labels, helps  projects reduce the lear
Suggested edits:

Inclusive labelling practices help create a more equitable and accessible environment for contributors from all backgrounds. Providing clear and informative labels helps projects reduce the learning curve for new contributors, encourages participation, and promotes diversity within the community.

2024-09-26 18:57 UTC, ElizabethN commented on focus-areas/project-and-community/issue-label-inclusivity.md
> +
Suggested edit:

- Identify the published list of issue labels used for each project
   - *General labels* identify general needs of the project (e.g., *Feature*, *Bug*, and *Documentation*)
   - *Newcomer-friendly labels* identify issues that are appropriate for first-time contributors (e.g., *newcomer*, *good first issue*)
   - *Skill labels* identify skills needed (e.g, *Java*, *Python*, *HTML*, *machine learning*)

- Observe the frequency of each label used across issues in a project

2024-09-26 18:57 UTC, ElizabethN commented on focus-areas/project-and-community/issue-label-inclusivity.md
>  From: https://github.com/kubernetes/kubernetes/labels
Can you please remove this line?

2024-09-26 18:57 UTC, ElizabethN commented on focus-areas/project-and-community/issue-label-inclusivity.md
>  - Type of label
Can you change this to "none identified."

2024-09-27 22:44 UTC, peculiaruc commented
All comments resolved

2024-10-01 13:24 UTC, ElizabethN approved these changes

2024-10-01 13:24 UTC, merged