New Metrics Update: Sponsorship.md
chaoss/wg-dei pull request #528
Opened 2024-09-18 08:42 UTC by peculiaruc

Updated the Organizational Influence using the new metrics template

- Tweak the description and the objective sections to form the Overview section.
- Page not found -> The Key Role of Sponsorship:
[https://inclusion.slac.stanford.edu/sites/default/files/The_Key_Role_of_a_Sponsorship_for_Diverse_Talent.pd]
- Page nor found -> Perceived unfairness is a major reason to leave a community
https://www.kaporcenter.org/tech-leavers/

2024-09-26 18:37 UTC, germonprez commented on focus-areas/leadership/sponsorship.md
> +Sponsoring measures the number of projects or community member who receive sponsorship—where a sponsor within or outside the community uses their reputation to create opportunities for the sponsee to
Suggested edits: 

Sponsorship measures the number of projects or community member who receive support—where a sponsor within or outside the community uses their reputation to create opportunities for sponsored people to advance. Data points include the number of active sponsorships, the progress of sponsored people (e.g., role advancement), and the diversity of sponsored individuals. Sponsorship helps retain members, grow contributors, and foster leadership development.

2024-09-26 18:42 UTC, germonprez commented on focus-areas/leadership/sponsorship.md
>    - Likert scale [1-x] item: How effective is the sponsorship program?
Please update all questions to these three new questions: 

  - Does your community have a sponsorship program and, if so, do you have a process by which people can apply? 
  - Who are you hoping to sponsor? 
  - Has sponsorship helped community members advance in their project roles?

2024-09-26 18:43 UTC, ElizabethN requested changes

2024-09-26 18:43 UTC, ElizabethN commented on focus-areas/leadership/sponsorship.md
> +To edit this metric please [submit a Change Request here](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/leadership/sponsorship.md)
Can you make sure this path is right? We changed from master to main a while back. The link technically still works, but it should match what it actually is.

2024-09-26 18:43 UTC, ElizabethN commented on focus-areas/leadership/sponsorship.md
> +Sponsorship ensures newer or less active members gain visibility and opportunities, strengthening community bonds and reducing turnover. sponsorship plays a critical role by supporting members from d
Suggested edits:
Sponsorship ensures newer or less active members gain visibility and opportunities, strengthens community bonds, and reduces turnover.  Sponsored people are 90 percent less likely to perceive bias in a community [1](https://fortune.com/2017/07/13/implicit-bias-perception-costs-companies/). Sponsorship also ensures diverse voices are promoted, ultimately creating a more inclusive and equitable community culture.

2024-09-26 21:19 UTC, peculiaruc commented on focus-areas/leadership/sponsorship.md
> +To edit this metric please [submit a Change Request here](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/leadership/sponsorship.md)
Added the right path

2024-09-26 21:20 UTC, peculiaruc commented on focus-areas/leadership/sponsorship.md
>    - Likert scale [1-x] item: How effective is the sponsorship program?
Done

2024-09-26 21:40 UTC, peculiaruc commented
All comments resolved

2024-11-07 17:57 UTC, ElizabethN approved these changes

2024-11-07 17:57 UTC, merged